  slam_toolbox:
     ros__parameters:
       # General Parameters
       use_sim_time: true
       
       # Robot frame_ids
       base_frame: base_link
       map_frame: map
       odom_frame: odom
       
       # Process mode (async is good for development/simulation)
       mode: async
       debug_logging: false
       
       # SLAM Mode Settings
       map_update_interval: 5.0
       resolution: 0.05
       max_laser_range: 12.0
       minimum_time_interval: 0.5
       transform_timeout: 0.2
       tf_buffer_duration: 30.
       stack_size_to_use: 40000000
       enable_interactive_mode: false
       
       # Loop closure parameters
       loop_search_maximum_distance: 10.0
       do_loop_closing: true
       
       # Scan matching parameters
       use_scan_matching: true
       use_scan_barycenter: true
       minimum_travel_distance: 0.5
       minimum_travel_heading: 0.5
       scan_buffer_size: 10
       scan_buffer_maximum_scan_distance: 10.0
       link_match_minimum_response_fine: 0.1
       link_scan_maximum_distance: 1.5
       loop_search_minimum_response: 0.35
       
       # Correlation parameters
       correlation_search_space_dimension: 0.5
       correlation_search_space_resolution: 0.01
       correlation_search_space_smear_deviation: 0.1
       
       # Correlation parameters - coarse search
       coarse_search_space_dimension: 0.5
       coarse_search_space_resolution: 0.05
       coarse_search_space_smear_deviation: 0.5
       
       # Scan topic from LIDAR 
       scan_topic: /scan
       
       # Optimization parameters
       optimize_on_first_loop: true
       
       # Visualization
       enable_detailed_type_information: false