/**:
  ros__parameters:
    topics:
      joystick:
        topic: /cmd_vel_joy
        timeout: 0.5
        priority: 100
      navigation:
        topic: /cmd_vel
        timeout: 0.5
        priority: 10
    
    # publisher:
    #   topic: /diff_cont/cmd_vel_unstamped
    #   timeout: 0.5